FROM tomcat:9.0.20

MAINTAINER saikrishna.ura@gmail.com

COPY ./food-app /usr/local/tomcat/webapps/food-app

COPY ./tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

COPY ./context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml

WORKDIR /usr/local/tomcat/webapps/food-app

EXPOSE 8081

CMD ["catalina.sh", "run"]
